bindAddress: :53535
debugHTTPAddress: :56565
dohEnabled: true
primaryDNS:
  - name: cn
    address: smartdns:6053
    protocol: udp
    socks5Address: ''
    timeout: 6
    ednsClientSubnet:
      policy: auto
      externalIP: ''
      noCookie: true
alternativeDNS:
  - name: global
    address: smartdns:6553
    protocol: udp
    socks5Address: ''
    timeout: 6
    ednsClientSubnet:
      policy: auto
      externalIP: ''
      noCookie: true
onlyPrimaryDNS: false
ipv6UseAlternativeDNS: false
alternativeDNSConcurrent: true
whenPrimaryDNSAnswerNoneUse: primaryDNS
ipNetworkFile:
  primary: /overture/china_ip.txt
  alternative: /overture/china_ip.txt
domainFile:
  primary: /overture/china_list.txt
  alternative: /overture/gfw_list.txt
  matcher: suffix-tree
hostsFile:
  hostsFile: /overture/hosts_sample
  finder: full-map
minimumTTL: 0
domainTTLFile: /overture/domain_ttl_sample
cacheSize: 0
cacheRedisUrl:
cacheRedisConnectionPoolSize:
rejectQType:
  - 255
